name: CiCd

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        example: [src/main.cpp]

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          wget https://github.com/skaygin/ArduinoShell/archive/refs/heads/main.zip -O /tmp/ashell.zip
          unzip /tmp/ashell.zip -d /tmp

      - name: Run PlatformIO
        run: pio ci --lib="/tmp/ArduinoShell-main/lib/ArduinoShell/src" --board=uno
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
